"""
Regenerate the example transcripts and their expected outputs by running the real
pipeline against each bundled sample. Run from the repo root:

    python test_examples/_generate.py

Writes ex{n}.txt (transcript), ex{n}_out.json (full structured output), and
ex{n}_out.md (human-readable) for each sample. Uses the LLM if OPENAI_API_KEY is set,
otherwise the deterministic mock engine.
"""
import json
import os
import sys

HERE = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(HERE, "..", "backend"))

import agent  # noqa: E402
from samples import SAMPLES  # noqa: E402

# stable order: the debt-collection headline example first
ORDER = ["debt_collection", "sales", "customer_support", "general_meeting"]


def md(result: dict, key: str) -> str:
    r = result
    L = [f"# Expected output — {SAMPLES[key]['label']}", ""]
    L += [f"- **domain:** `{r['domain']}` — handled by **{r['domain_agent']}**",
          f"- **routing rationale:** {r['domain_rationale']}",
          f"- **anchor date:** {r['anchor_date']}  ·  **lines:** {r['segment_count']}",
          f"- **tag:** {r['tag']}", "", "## Summary", "", r["summary"], ""]

    if r["decisions"]:
        L += ["## Decisions", ""]
        for d in r["decisions"]:
            L += [f"- {d['decision']}  \n  _lines {d['source_ids']}_"]
        L += [""]

    if r["action_items"]:
        L += ["## Action items", ""]
        for a in r["action_items"]:
            L += [f"- **{a['task']}**  \n  owner: `{a['owner']}` · start: `{a['start']}` · "
                  f"due: `{a['due']}` · _lines {a['source_ids']}_"]
        L += [""]

    if r["blockers"]:
        L += ["## Blockers", ""]
        for b in r["blockers"]:
            L += [f"- {b['blocker']}  \n  _lines {b['source_ids']}_"]
        L += [""]

    if r["compliance_observations"]:
        L += ["## Compliance observations", ""]
        for o in r["compliance_observations"]:
            L += [f"- **[{o['status']}]** {o['note']}  \n  _lines {o['source_ids']}_"]
        L += [""]

    if r["items_needing_human_review"]:
        L += ["## Needs human review", ""]
        for x in r["items_needing_human_review"]:
            L += [f"- **({x['category']})** {x['item']}  \n  reason: {x['reason']}  \n  _lines {x['source_ids']}_"]
        L += [""]

    if r["recommended_next_steps"]:
        L += ["## Recommended next steps", ""]
        L += [f"- {s}" for s in r["recommended_next_steps"]] + [""]

    L += ["---", f"_Generated by running the pipeline (mode: "
          f"{'LLM ' + agent.MODEL if agent.USE_LLM else 'mock'}) against `ex{ORDER.index(key)+1}.txt`._"]
    return "\n".join(L)


def main():
    print(f"mode: {'LLM ' + agent.MODEL if agent.USE_LLM else 'MOCK'}")
    for i, key in enumerate(ORDER, start=1):
        s = SAMPLES[key]
        open(os.path.join(HERE, f"ex{i}.txt"), "w", encoding="utf-8").write(s["transcript"] + "\n")

        result = None
        for ev in agent.run_stream(s["transcript"], s["meeting_date"]):
            if ev.get("node") == "result":
                result = ev["result"]

        with open(os.path.join(HERE, f"ex{i}_out.json"), "w", encoding="utf-8") as f:
            json.dump(result, f, indent=2, ensure_ascii=False)
        open(os.path.join(HERE, f"ex{i}_out.md"), "w", encoding="utf-8").write(md(result, key))
        print(f"  ex{i} [{key}] -> {len(result['action_items'])} actions, "
              f"{len(result['items_needing_human_review'])} review items")


if __name__ == "__main__":
    main()
